apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: go-app
spec:
  secretName: ingress-certificate
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: go-app.example.com
  dnsNames:
    - go-app.example.com
  duration: 2160h
  renewBefore: 360h
