apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-gin
  namespace: go-app
  labels:
    app: web-server-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-gin
  template:
    metadata:
      labels:
        app: web-server-gin
    spec:
      containers:
        - name: web-server-gin
          image: xomrkob/web-server-gin:0.1.1-beaaa6ba0d6627321dd0b2639ad614c775fad8fa
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50051
          env:
            - name: SERVER_ADDR
              value: ":8080"
            - name: DOMAIN
              value: go-app.example.com
            - name: DB_HOST
              value: postgresql.go-app.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "database1"
            - name: CASBIN_MODEL
              value: "/app/config/model.conf"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_USER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: JWT_SECRET
            - name: JWT_ACCESS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: ACCESS_PRIVATE_KEY
            - name: JWT_ACCESS_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: ACCESS_PUBLIC_KEY
            - name: JWT_REFRESH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: REFRESH_PRIVATE_KEY
            - name: JWT_REFRESH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: REFRESH_PUBLIC_KEY
            - name: JWT_REFRESH_TOKEN_EXPIRY
              value: "168h"
            - name: JWT_ACCESS_TOKEN_EXPIRY
              value: "60m"
            - name: AUTH_SERVICE_ADDRESS
              value: web-server-gin-service:50051
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
