apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-gin
  namespace: go-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/http2-listener: "true"
    cert-manager.io/issuer: "ca-issuer"
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: auth-tls
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /auth/.*
            pathType: Prefix
            backend:
              service:
                name: web-server-gin-service
                port:
                  number: 80
