apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: go-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASS: TWFzdGVyMTIzNA==
  JWT_SECRET: TWFzdGVyMTIzNA==
stringData:
  ACCESS_PRIVATE_KEY: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCr3hYIjvDAG8II
    tLFDhQQpWNk6CHKjjQbIJ50t+5f3NQI8I6XDKUO4LIO/11J9i22AXenRgJwi+uCw
    oAUh/9mJemlX3RKyO0jfz4+srGURfLywT47hbIZdCyKuJaK+RioDtCtVqxTEvSdE
    8xMC+EKyasu/eX8FSnO7fO3LW9FQ0PqlPE1L3jG8AjPBVisqGIUJ4DLTw21ET8+E
    Xj5Bnfds3r2v66zX34+JtFNjyb+dQC1adYoPgmSfuPvbAHVk5Ilq7Vq3hqcnP0oe
    q/C6xbt94Z5B+3uns44lPkwWhH1SFew/WmaCcAu7/75nC5arIbY2O4lSs5NO34hr
    Ul9xOQbXAgMBAAECggEABSE47u92Ex3ULrAjle+h8Xcwuj4A6FqWVO7ajtuyePmK
    XaL1i+77q1y0xmSV/NMZ2E0bsTOeaJ+siWKoh8L1sL57gQv2ecuYMyOKvWCPfoEG
    tr9HjsXo95AuBemjD/yf8DVcxI7sxne1qAxJr64bFSBn5wkO0ZvolJq34RJ8zsv2
    SEVA62sUjLz1NukpWk59oFoEZV8A0lkW7nejUynbVdnlfipg15Bnicx/cOT9UkXv
    n1HVsorhyTO74DnFGM/GsVsHn1iajNJGH759IAXEOq5wn6VBPtxnGPT9q9e6fInM
    /VYKZfndguUXHbm4sGOBr2wLNNOD5G/FyCyAHtAjAQKBgQDbFsJeFxw36reo99dl
    YxffIPCldB8bEzjj8vA28U81XWAKSHsThlEqOocKa2aYgJJ7rGnEoGTwz1TpPw1K
    WoSQAHvMdPKjUOwhxiK6eDK6gaqGoerm/FWzIdjhm5QRvhrWbMJj4O27mnXZUZpO
    8V3PDkF9qtTXqQG8rM/U78ZFAQKBgQDI0q60G5CTWt0Pbj2ntP0fkEbj8oiQXNa6
    1jUWPv7fn6WhMQo0ASezHNarFiTNj40OFO47JNWc2D2csr3tGdWg0u3p7SrR7qNI
    9Pq/fdxTNMulKnp/RQfuEtc0vVFakacnKI9hml4/BKDwqfcHtumtHEKE4xLy4epU
    v6n17JYT1wKBgQCOE6BQbCQ8jtYzmSXx9eURKcdlRHy3jiuih3UH7E01iiwx/vbx
    nnUcMYBJXYTW+OoFkbW1cV6EW6/w4pa31SOKTwX5fQ2so1m+PUNgMXqUQGpZjL9M
    s+7Pj++Zvs6zAtlcnIMjSkZhFrW+DJFJCHWRROlrmVEV2d/qfxb4O9YUAQKBgD2Y
    SRda4QQhOW5TLLv0ijKVKPkfWX2VzBKwQsYY+kmSiNWg2fVLaWbJcJo3B4C5B9WK
    2+ruCEq8FGGsfQ5s/xX9vBUkth5/qDtnUEVNkDdBGTkGh13jyWPfCXzWmE5EIFWl
    XhzcoQ2JGOfX6bnHA3MiGNDzaMtwOVRXGQUh1IIvAoGBAIv5+a+LBUPJ90anBRxy
    GtSy+cxC+8TvSSK2tawyVB2H/61veqYjAs7sDVm1XXyywEB/YPHiUwP+TbHpB5RX
    5mc6wms8rapi7HOyVHJLYPPL0R2BOhFgByaYRJQ8eYW8Ol4+Ho8swgdFvqdOx4vK
    TB9nvfVct0qfu0SfQ0aHDwav
    -----END PRIVATE KEY-----
  ACCESS_PUBLIC_KEY: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq94WCI7wwBvCCLSxQ4UE
    KVjZOghyo40GyCedLfuX9zUCPCOlwylDuCyDv9dSfYttgF3p0YCcIvrgsKAFIf/Z
    iXppV90SsjtI38+PrKxlEXy8sE+O4WyGXQsiriWivkYqA7QrVasUxL0nRPMTAvhC
    smrLv3l/BUpzu3zty1vRUND6pTxNS94xvAIzwVYrKhiFCeAy08NtRE/PhF4+QZ33
    bN69r+us19+PibRTY8m/nUAtWnWKD4Jkn7j72wB1ZOSJau1at4anJz9KHqvwusW7
    feGeQft7p7OOJT5MFoR9UhXsP1pmgnALu/++ZwuWqyG2NjuJUrOTTt+Ia1JfcTkG
    1wIDAQAB
    -----END PUBLIC KEY-----
  REFRESH_PRIVATE_KEY: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeb+G7W1JMbKIk
    i88C/NSbH3TZ3JlMtoMsAbwaTqeTVGgvRdptBNAs6tQsVz0sCKFmu3bp84wOR06j
    ZzW9txZ79Yam5BSMSXYQFbMVRWq50qSUfuLPo2BYwucZ5CCYFTG0iS7FSxlY/pTm
    trXR+A1jVDP1Bk2idlff9w+Re2yYtgyqdpA64ohYtasHaQMHum7rk9nCDkQMny4x
    8oxv9ABhPP+7cqmdYvuNfS4J/toQ6igOWynPg9PR5kQPjl5+4usd2TNBkzIoo2yG
    poRY+KxwH2W2rTmVGBPy07Yw+UY41KLPsAOVU3IihqZfgI8/LDgOfs5cDtdbi3vS
    jEkK8r9ZAgMBAAECggEAHHGpJ3i3ju9LUqoQKD0lgMqmeh+D+PPT1UJJiAGr2yKt
    ifIASvWVG1FSHXNwbpuR7B2nyKXssHy82RdfH2n0tZhBhkDfQcs5DjiAJIWybp25
    jwWkwlGNhfwyajSqWFhJeWEben4ueRtg9hnCKV3zdFK1rC0Iq3A/r3Ob6YojammM
    H83WTZ02q0m57LF2/fpWKTu/l/DuF0RkYJ6avuHUpbPcjAF+/qEJ7h9WeDaU7db+
    4P0AKq4SHLVM+spi1U8bw3M9lwEsTTssldLbjC7tUd+xyuVWgYQBR07PIyzDslAz
    6r+6MqGD2BQXwsu2e526MIYqh89mYnNjWjqEYHA+SwKBgQD54oFwi+LBroy73aCB
    0RWzgFwsutXDmBGfRtriLesfUEsk2jKupBltgXRgpw15+/rhRah3UUpvnrmsVeQl
    k/AdobsjO4ygtGkks1dkay5YRXIhy02gpN9BpNkJ45HdDSINy5MMIo4U17hcMPQg
    D8IPZT6NNyEx7UNd/CxCFy6O9wKBgQDj4Wtx121+GZlTZ+9HVBSywa8PK5YY3TFN
    Ng466gaxs68l1Mz4cydqqyVkPecnKN50IbNhO3TL7elKqtqLSDXlrSU5g6hpo4fU
    eskKyf1rMKX5iNMRhwxGW9hLQTQQqHhl6fXeMLDp9XGhSlESofmk/tVG31/qvyl/
    xJH0A62ALwKBgQCpMGB9qGkGxD1LcdqcKsnruGwwaOwVO6Aq3JmU7Iw2rnHCaO5J
    6pfA2hbG3jS0tBSAdF6FMwgYHTsP4TPQ8aJxHbEMQOSNZrmN/NOeDSfa4mJNWU6d
    BySWWJwPIwL+zUaSWpScccULfae42/hewOye6ej5Sityl3e2aeg5c2K1rwKBgF6e
    nspqNOCDKJLlOQlY9C81FMcrxesVDP+OTmJQAe+POE5xCZqv1dIItkHlIjG0WonF
    5IGe+mQiqReD0bK7jQWM20QCUs9qQ2AKi6ebL0purLvsABfrB0G/qRO2QzQXf8Zx
    WtGjThIXA9OA1CD0eH/2AACph14lecm/iQrU7BmpAoGBAOcCSXINRtoNt9wOLl2H
    95e3nL3wEV6YpJxACuPYt0VPKzXE7/t/gO2Ws+3+zjGzEUPFAtyp3eMrdS4gBttl
    QveU1E8GgwBdjGwHFNds9HRCbJzTnCmJt1cV31TkhFH1Z9NR2ALbxRlfjQggN3G8
    O87PbKsc5mw+Q958r6LHs9Xx
    -----END PRIVATE KEY-----
  REFRESH_PUBLIC_KEY: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3m/hu1tSTGyiJIvPAvzU
    mx902dyZTLaDLAG8Gk6nk1RoL0XabQTQLOrULFc9LAihZrt26fOMDkdOo2c1vbcW
    e/WGpuQUjEl2EBWzFUVqudKklH7iz6NgWMLnGeQgmBUxtIkuxUsZWP6U5ra10fgN
    Y1Qz9QZNonZX3/cPkXtsmLYMqnaQOuKIWLWrB2kDB7pu65PZwg5EDJ8uMfKMb/QA
    YTz/u3KpnWL7jX0uCf7aEOooDlspz4PT0eZED45efuLrHdkzQZMyKKNshqaEWPis
    cB9ltq05lRgT8tO2MPlGONSiz7ADlVNyIoamX4CPPyw4Dn7OXA7XW4t70oxJCvK/
    WQIDAQAB
    -----END PUBLIC KEY-----
