apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-gin
  namespace: go-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/http2-listener: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_content_type = "application/grpc") {
        set $backend_protocol "grpc";
      }
    cert-manager.io/issuer: "ca-issuer"
spec:
  tls:
    - hosts:
        - go-app.example.com
      secretName: ingress-certificate
  ingressClassName: nginx
  rules:
    - host: go-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-server-gin-service
                port:
                  number: 80
